version: '3'

services:
  db:
    image: 'zcube/bitnami-compat-mongodb'
    container_name: mongodb_store_api
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=192.168.0.110
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_data:/bitnami/mongodb

volumes:
  mongo_data:
    driver: local